CREATE PROFILE unlimited LIMIT
SESSIONS_PER_USER UNLIMITED
  CPU_PER_SESSION UNLIMITED
  CPU_PER_CALL UNLIMITED
  CONNECT_TIME UNLIMITED
  IDLE_TIME UNLIMITED
  LOGICAL_READS_PER_SESSION UNLIMITED
  LOGICAL_READS_PER_CALL UNLIMITED
  COMPOSITE_LIMIT UNLIMITED
  PRIVATE_SGA UNLIMITED
  FAILED_LOGIN_ATTEMPTS unlimited
  PASSWORD_LIFE_TIME UNLIMITED
  PASSWORD_REUSE_TIME unlimited
  PASSWORD_REUSE_MAX unlimited
  PASSWORD_LOCK_TIME UNLIMITED  
  PASSWORD_GRACE_TIME unlimited
  PASSWORD_VERIFY_FUNCTION null;
